### ISSUE TITLE
Getting lot of KeyError: "temperature"

### ISSUE THREAD

**Issue by rafaelrs** [fieldOfView/OctoPrintPlugin#39]
```
2017-06-07 01:29:04,221 - CRITICAL - cura.CrashHandler.show [36]: An uncaught exception has occurred!
2017-06-07 01:29:04,222 - CRITICAL - cura.CrashHandler.show [39]: Traceback (most recent call last):
2017-06-07 01:29:04,223 - CRITICAL - cura.CrashHandler.show [39]:   File "/home/rafaelrs/AddProgs/Cura/Cura-2.5.0/usr/bin/plugins/plugins/OctoPrintPlugin/OctoPrintOutputDevice.py", line 527, in _onRequestFinished
2017-06-07 01:29:04,224 - CRITICAL - cura.CrashHandler.show [39]:     temperature = json_data["temperature"]["tool%d" % index]["actual"] if ("tool%d" % index) in json_data["temperature"] else 0
2017-06-07 01:29:04,226 - CRITICAL - cura.CrashHandler.show [39]: KeyError: 'temperature'
2017-06-07 01:29:06,376 - CRITICAL - cura.CrashHandler.show [36]: An uncaught exception has occurred!
2017-06-07 01:29:06,377 - CRITICAL - cura.CrashHandler.show [39]: Traceback (most recent call last):
2017-06-07 01:29:06,379 - CRITICAL - cura.CrashHandler.show [39]:   File "/home/rafaelrs/AddProgs/Cura/Cura-2.5.0/usr/bin/plugins/plugins/OctoPrintPlugin/OctoPrintOutputDevice.py", line 527, in _onRequestFinished
2017-06-07 01:29:06,380 - CRITICAL - cura.CrashHandler.show [39]:     temperature = json_data["temperature"]["tool%d" % index]["actual"] if ("tool%d" % index) in json_data["temperature"] else 0
2017-06-07 01:29:06,382 - CRITICAL - cura.CrashHandler.show [39]: KeyError: 'temperature'
2017-06-07 01:29:08,165 - CRITICAL - cura.CrashHandler.show [36]: An uncaught exception has occurred!
2017-06-07 01:29:08,166 - CRITICAL - cura.CrashHandler.show [39]: Traceback (most recent call last):
2017-06-07 01:29:08,167 - CRITICAL - cura.CrashHandler.show [39]:   File "/home/rafaelrs/AddProgs/Cura/Cura-2.5.0/usr/bin/plugins/plugins/OctoPrintPlugin/OctoPrintOutputDevice.py", line 527, in _onRequestFinished
2017-06-07 01:29:08,168 - CRITICAL - cura.CrashHandler.show [39]:     temperature = json_data["temperature"]["tool%d" % index]["actual"] if ("tool%d" % index) in json_data["temperature"] else 0
2017-06-07 01:29:08,169 - CRITICAL - cura.CrashHandler.show [39]: KeyError: 'temperature'
2017-06-07 01:29:10,184 - CRITICAL - cura.CrashHandler.show [36]: An uncaught exception has occurred!
2017-06-07 01:29:10,186 - CRITICAL - cura.CrashHandler.show [39]: Traceback (most recent call last):
2017-06-07 01:29:10,187 - CRITICAL - cura.CrashHandler.show [39]:   File "/home/rafaelrs/AddProgs/Cura/Cura-2.5.0/usr/bin/plugins/plugins/OctoPrintPlugin/OctoPrintOutputDevice.py", line 527, in _onRequestFinished
2017-06-07 01:29:10,188 - CRITICAL - cura.CrashHandler.show [39]:     temperature = json_data["temperature"]["tool%d" % index]["actual"] if ("tool%d" % index) in json_data["temperature"] else 0
2017-06-07 01:29:10,189 - CRITICAL - cura.CrashHandler.show [39]: KeyError: 'temperature'
2017-06-07 01:29:12,167 - CRITICAL - cura.CrashHandler.show [36]: An uncaught exception has occurred!
2017-06-07 01:29:12,168 - CRITICAL - cura.CrashHandler.show [39]: Traceback (most recent call last):
2017-06-07 01:29:12,170 - CRITICAL - cura.CrashHandler.show [39]:   File "/home/rafaelrs/AddProgs/Cura/Cura-2.5.0/usr/bin/plugins/plugins/OctoPrintPlugin/OctoPrintOutputDevice.py", line 527, in _onRequestFinished
2017-06-07 01:29:12,171 - CRITICAL - cura.CrashHandler.show [39]:     temperature = json_data["temperature"]["tool%d" % index]["actual"] if ("tool%d" % index) in json_data["temperature"] else 0
2017-06-07 01:29:12,173 - CRITICAL - cura.CrashHandler.show [39]: KeyError: 'temperature'
```

Linux - Fedora 25
OctoPrint 1.3.4
Cura 2.5.0 (here i didn't understood how to put plugin to app when i start it from appImage, i just unpacked this appImage, putted plugin to ./Cura-2.5.0/usr/bin/plugins/plugins/OctoPrintPlugin and started ./Cura-2.5.0/AppRun )

**Comment by fieldOfView** [comment]
I'll look in to it. Apparently your octoprint instance is reporting data, but no temperatures. Anything special about the printer I should know about? Is the plugin working otherwise? (ie: can you send a print to octoprint from inside Cura?)

On installing the plugin, you can put it in the configuration folder (~/.local/shared/cura/plugins ?) 
That folder should alreadt have a subfolder named "plugins".

**Comment by fieldOfView** [comment]
The errors should be fixed now, in the branches 2.5, 2.6 and master.

**Comment by rafaelrs** [comment]
Yes, i can send to print and it prints good. But it was showing no printing progress, and seems like not always catches temperatures (i didn't saw hotend temp ever for example). Nothing special in my printer, it's just FLSUN cube printer based on MKS Gen-L board with Marling 1.1.0 RC7

Just tried your last fix, still don't see hotend temp, and printing progress is zero always and i see these errors:

`2017-06-11 00:56:57,997 - CRITICAL - cura.CrashHandler.show [36]: An uncaught exception has occurred!
2017-06-11 00:56:57,998 - CRITICAL - cura.CrashHandler.show [39]: Traceback (most recent call last):
2017-06-11 00:56:58,000 - CRITICAL - cura.CrashHandler.show [39]:   File "/home/rafaelrs/AddProgs/Cura/Cura-2.5.0/usr/bin/plugins/plugins/OctoPrintPlugin/OctoPrintOutputDevice.py", line 535, in _onRequestFinished
2017-06-11 00:56:58,001 - CRITICAL - cura.CrashHandler.show [39]:     if json_data["state"]["flags"]["error"]:
2017-06-11 00:56:58,002 - CRITICAL - cura.CrashHandler.show [39]: TypeError: string indices must be integers
`

That's how it looks: [http://storage2.static.itmages.com/i/17/0610/h_1497132490_9360510_a7f0d01ff7.png](url)

**Comment by fieldOfView** [comment]
Could you try the following URL in your browser, and send me the results?
```http://[octoprint address]/api/printer?apikey=[api-key]```
eg: ```http://octopi.local/api/printer?apikey=73C7E2006D25AA71AE31239F28549F14```

**Comment by rafaelrs** [comment]
Sorry for delay, just reached my printer output:

`$ curl http://3dprinter.home:5000/api/printer?apikey=********************************
{
  "sd": {
    "ready": false
  }, 
  "state": {
    "flags": {
      "closedOrError": false, 
      "error": false, 
      "operational": true, 
      "paused": false, 
      "printing": true, 
      "ready": false, 
      "sdReady": false
    }, 
    "text": "Printing"
  }, 
  "temperature": {
    "bed": {
      "actual": 45.4, 
      "offset": 0, 
      "target": 45.0
    }, 
    "tool0": {
      "actual": 214.9, 
      "offset": 0, 
      "target": 215.0
    }
  }
}`

**Comment by fieldOfView** [comment]
That looks like correct output, but apparently it is not what the plugin is getting from OctoPrint. I'll add some more logging to find out what is going on.

**Comment by fieldOfView** [comment]
I have updated the 2.5 branch to add some more logging. Could you try it out? I am specifically looking for debug log entries that start with ```Received incomplete json from OctoPrint:```

**Comment by rafaelrs** [comment]
Here you go:

`2017-06-12 22:54:29,611 - DEBUG - OctoPrintPlugin.OctoPrintOutputDevice._onRequestFinished [551]: Received incomplete json from OctoPrint: {'progress': {'filepos': None, 'completion': None, 'printTime': None, 'printTimeLeft': None}, 'state': 'Printing', 'job': {'estimatedPrintTime': None, 'lastPrintTime': None, 'filament': None, 'averagePrintTime': None, 'file': {'origin': 'local', 'path': 'FLP_auffahrt.gcode', 'date': 1497297242, 'name': 'FLP_auffahrt.gcode', 'size': 1702449}}}
2017-06-12 22:54:31,558 - DEBUG - OctoPrintPlugin.OctoPrintOutputDevice._onRequestFinished [551]: Received incomplete json from OctoPrint: {'progress': {'filepos': None, 'completion': None, 'printTime': None, 'printTimeLeft': None}, 'state': 'Printing', 'job': {'estimatedPrintTime': None, 'lastPrintTime': None, 'filament': None, 'averagePrintTime': None, 'file': {'origin': 'local', 'path': 'FLP_auffahrt.gcode', 'date': 1497297242, 'name': 'FLP_auffahrt.gcode', 'size': 1702449}}}
`

**Comment by fieldOfView** [comment]
Doh!

It breaks because you have the string "printer" in the hostname. I'll create a fix.

**Comment by fieldOfView** [comment]
Should be fixed now. Can you give it another go?

**Comment by rafaelrs** [comment]
Just checked. Works fine, shows everything. Thanks a lot!

**Comment by fieldOfView** [comment]
Thanks for helping me get to the bottom of this.
